/* 
* Generated by
* 
*      _____ _          __  __      _     _
*     / ____| |        / _|/ _|    | |   | |
*    | (___ | | ____ _| |_| |_ ___ | | __| | ___ _ __
*     \___ \| |/ / _` |  _|  _/ _ \| |/ _` |/ _ \ '__|
*     ____) |   < (_| | | | || (_) | | (_| |  __/ |
*    |_____/|_|\_\__,_|_| |_| \___/|_|\__,_|\___|_|
*
* The code generator that works in many programming languages
*
*			https://www.skaffolder.com
*
*
* You can generate the code from the command-line
*       https://npmjs.com/package/skaffolder-cli
*
*       npm install -g skaffodler-cli
*
*   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *
*
* To remove this comment please upgrade your plan here: 
*      https://app.skaffolder.com/#!/upgrade
*
* Or get up to 70% discount sharing your unique link:
*       https://app.skaffolder.com/#!/register?friend=5e9d798a82f82d390e778bf8
*
* You will get 10% discount for each one of your friends
* 
*/
package com.temp.db.temp_db.entity.base;

/**
 * 
 * 
  _____                      _              _ _ _     _   _     _        __ _ _      
 |  __ \                    | |            | (_) |   | | | |   (_)      / _(_) |     
 | |  | | ___    _ __   ___ | |_    ___  __| |_| |_  | |_| |__  _ ___  | |_ _| | ___ 
 | |  | |/ _ \  | '_ \ / _ \| __|  / _ \/ _` | | __| | __| '_ \| / __| |  _| | |/ _ \
 | |__| | (_) | | | | | (_) | |_  |  __/ (_| | | |_  | |_| | | | \__ \ | | | | |  __/
 |_____/ \___/  |_| |_|\___/ \__|  \___|\__,_|_|\__|  \__|_| |_|_|___/ |_| |_|_|\___|
 
                                                                                   
 * DO NOT EDIT THIS FILE!! 
 *
 *  FOR CUSTOMIZE TweetBase PLEASE EDIT ../Tweet.java
 * 
 *  -- THIS FILE WILL BE OVERWRITTEN ON THE NEXT SKAFFOLDER CODE GENERATION --
 * 
 */
 

/**
 * This is the model of Tweet object
 * 
 */
 
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Date;
import java.math.BigDecimal;


import org.springframework.jdbc.core.RowMapper;
import com.temp.db.temp_db.entity.Tweet;

public class TweetBase implements RowMapper<Tweet>{
	
	private Long _id;
	
	// Attributes
    private String Text;
    private String author;
    private Date date;
    private BigDecimal latt;
    private BigDecimal longi;
    private String sentiment;
	
	
	
	@Override
	public Tweet mapRow(ResultSet rs, int rowNum) throws SQLException {
		
		Tweet obj = new Tweet();
		try {
			obj.set_id(rs.getLong("id"));
			obj.setText(rs.getString("Text"));
			obj.setAuthor(rs.getString("author"));
			obj.setDate(rs.getDate("date"));
			obj.setLatt(rs.getBigDecimal("latt"));
			obj.setLongi(rs.getBigDecimal("longi"));
			obj.setSentiment(rs.getString("sentiment"));
			
        	
		}
		catch(Exception e) {
			e.printStackTrace();
		}
		return obj;
	}


	public Long get_id() {
		return _id;
	}

	public void set_id(Long _id) {
		this._id = _id;
	}
	
	public String getText() {
		return Text;
	}


	public void setText(String Text) {
		this.Text = Text;
	}
	public String getAuthor() {
		return author;
	}


	public void setAuthor(String author) {
		this.author = author;
	}
	public Date getDate() {
		return date;
	}


	public void setDate(Date date) {
		this.date = date;
	}
	public BigDecimal getLatt() {
		return latt;
	}


	public void setLatt(BigDecimal latt) {
		this.latt = latt;
	}
	public BigDecimal getLongi() {
		return longi;
	}


	public void setLongi(BigDecimal longi) {
		this.longi = longi;
	}
	public String getSentiment() {
		return sentiment;
	}


	public void setSentiment(String sentiment) {
		this.sentiment = sentiment;
	}
	
    
    
    
    
}