/* 
* Generated by
* 
*      _____ _          __  __      _     _
*     / ____| |        / _|/ _|    | |   | |
*    | (___ | | ____ _| |_| |_ ___ | | __| | ___ _ __
*     \___ \| |/ / _` |  _|  _/ _ \| |/ _` |/ _ \ '__|
*     ____) |   < (_| | | | || (_) | | (_| |  __/ |
*    |_____/|_|\_\__,_|_| |_| \___/|_|\__,_|\___|_|
*
* The code generator that works in many programming languages
*
*			https://www.skaffolder.com
*
*
* You can generate the code from the command-line
*       https://npmjs.com/package/skaffolder-cli
*
*       npm install -g skaffodler-cli
*
*   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *
*
* To remove this comment please upgrade your plan here: 
*      https://app.skaffolder.com/#!/upgrade
*
* Or get up to 70% discount sharing your unique link:
*       https://app.skaffolder.com/#!/register?friend=5e9d798a82f82d390e778bf8
*
* You will get 10% discount for each one of your friends
* 
*/
import { Component } from '@angular/core';
import { OnInit } from '@angular/core';
// Import Services
import { TweetService } from '../../services/tweet.service';
// Import Models
import { Tweet } from '../../domain/temp_db/tweet';

// START - USED SERVICES
/**
* TweetService.list
*	@description CRUD ACTION list
*
*/
// END - USED SERVICES

/**
 * This component shows a list of Tweet
 * @class TweetListComponent
 */
@Component({
    selector: 'app-tweet-list',
    templateUrl: './tweet-list.component.html',
    styleUrls: ['./tweet-list.component.css']
})
export class TweetListComponent implements OnInit {
    list: Tweet[];
    search: any = {};
    idSelected: string;
    constructor(
        private tweetService: TweetService,
    ) { }

    /**
     * Init
     */
    ngOnInit(): void {
        this.tweetService.list().subscribe(list => this.list = list);
    }

    /**
     * Select Tweet to remove
     *
     * @param {string} id Id of the Tweet to remove
     */
    selectId(id: string) {
        this.idSelected = id;
    }

    /**
     * Remove selected Tweet
     */
    deleteItem() {
        this.tweetService.remove(this.idSelected).subscribe(data => this.list = this.list.filter(el => el._id !== this.idSelected));
    }

}
